logging:
  level:
    root: DEBUG

spring:
  application:
    name: fc-api
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  jpa:
    properties:
      hibernate:
        jdbc:
          time_zone: UTC
  liquibase:
    change-log: db/changelog/db.changelog-master.xml

server:
  error:
    include-stacktrace: NEVER

finance_environment: DEV # ${ENV}

management:
  endpoints:
    web:
      base-path: /