logging:
  level:
    root: DEBUG

spring:
  application:
    name: fc-api
  datasource:
    url: jdbc:postgresql://localhost:5432/fc?currentSchema=dashboard-dev
    username: puser
    password: psqlpassword
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        jdbc:
          time_zone: UTC
  liquibase:
    change-log: db/changelog/db.changelog-master.xml

server:
  error:
    include-stacktrace: NEVER

finance_environment: DEV # ${ENV}

management:
  endpoints:
    web:
      base-path: /